<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="WebForm2.aspx.cs" Inherits="EmployeeRegistration_09_01_2023.WebForm2" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
        <div>
             <asp:GridView ID="GridView1" runat="server" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" OnRowCancelingEdit="GridView1_RowCancelingEdit" OnRowDeleting="GridView1_RowDeleting" OnRowEditing="GridView1_RowEditing" OnRowUpdating="GridView1_RowUpdating" AutoGenerateColumns="False" OnSelectedIndexChanged="GridView1_SelectedIndexChanged" >
            <Columns>
          

            <asp:TemplateField HeaderText="FirstName">
                        <ItemTemplate>
                            <asp:Label  Text='<%# Eval("FirstName") %>' ID="lblfn"  runat="server"></asp:Label>
                        </ItemTemplate>
                        <EditItemTemplate>
                             <asp:label  Text='<%# Eval("FirstName") %>' ID="lblfn" runat="server"></asp:label>
                        </EditItemTemplate>
                    </asp:TemplateField>
                <asp:TemplateField HeaderText="MiddleName">
                    <ItemTemplate>
                        <asp:Label Text='<%# Eval("MiddleName") %>' Id="lblm" runat="server"></asp:Label>
                    </ItemTemplate>

                    <EditItemTemplate>
                        <asp:TextBox Text='<%# Eval("MiddleName") %>' Id="txtm" runat="server"></asp:TextBox>
                    </EditItemTemplate>
                </asp:TemplateField>

                 <asp:TemplateField HeaderText="LastName">
                    <ItemTemplate>
                        <asp:Label Text='<%# Eval("LastName") %>' Id="lbll" runat="server"></asp:Label>
                    </ItemTemplate>
                    <EditItemTemplate>
                        <asp:TextBox Text='<%# Eval("LastName") %>' Id="txtl" runat="server"></asp:TextBox>
                    </EditItemTemplate>
                </asp:TemplateField>
                 <asp:TemplateField HeaderText="FatherName">
                    <ItemTemplate>
                        <asp:Label Text='<%# Eval("FatherName") %>' Id="lblf" runat="server"></asp:Label>
                    </ItemTemplate>
                    <EditItemTemplate>
                        <asp:TextBox Text='<%# Eval("FatherName") %>' Id="txtf" runat="server"></asp:TextBox>
                    </EditItemTemplate>
                </asp:TemplateField>

                <asp:TemplateField HeaderText="DateOfBirth">
                    <ItemTemplate>
                        <asp:Label Text='<%# Eval("DateOfBirth") %>' Id="lblb" runat="server"></asp:Label>
                    </ItemTemplate>
                    <EditItemTemplate>
                        <asp:TextBox Text='<%# Eval("DateOfBirth") %>' Id="txtb" runat="server"></asp:TextBox>
                    </EditItemTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="Gender">
                    <ItemTemplate>
                        <asp:Label Text='<%# Eval("Gender") %>' Id="lblg" runat="server"></asp:Label>
                    </ItemTemplate>
                    <EditItemTemplate>
                        <asp:TextBox Text='<%# Eval("Gender") %>' Id="txtg" runat="server"></asp:TextBox>
                    </EditItemTemplate>
                </asp:TemplateField>
                <asp:TemplateField HeaderText="Religion">
                    <ItemTemplate>
                        <asp:Label Text='<%# Eval("Religion") %>' Id="lblR" runat="server"></asp:Label>
                    </ItemTemplate>
                    <EditItemTemplate>
                        <asp:TextBox Text='<%# Eval("Religion") %>' Id="txtR" runat="server"></asp:TextBox>
                    </EditItemTemplate>
                </asp:TemplateField>

                <asp:TemplateField HeaderText="Cast">
                    <ItemTemplate>
                        <asp:Label Text='<%# Eval("Cast") %>' Id="lblf" runat="server"></asp:Label>
                    </ItemTemplate>
                    <EditItemTemplate>
                        <asp:TextBox Text='<%# Eval("Cast") %>' Id="txtf" runat="server"></asp:TextBox>
                    </EditItemTemplate>
                </asp:TemplateField>

                <asp:TemplateField HeaderText="EducationalQualification">
                    <ItemTemplate>
                        <asp:Label Text='<%# Eval("EducationalQualification") %>' Id="lbled" runat="server"></asp:Label>
                    </ItemTemplate>
                    <EditItemTemplate>
                        <asp:TextBox Text='<%# Eval("EducationalQualification") %>' Id="txted" runat="server"></asp:TextBox>
                    </EditItemTemplate>
                </asp:TemplateField>
                
                 <asp:TemplateField HeaderText="MobileNumber">
                    <ItemTemplate>
                        <asp:Label Text='<%# Eval("MobileNumber") %>' Id="lblmo" runat="server"></asp:Label>
                    </ItemTemplate>
                    <EditItemTemplate>
                        <asp:TextBox Text='<%# Eval("MobileNumber") %>' Id="txtmo" runat="server"></asp:TextBox>
                    </EditItemTemplate>
                </asp:TemplateField>

                <asp:TemplateField HeaderText="Address">
                    <ItemTemplate>
                        <asp:Label Text='<%# Eval("Address") %>' Id="lbladd" runat="server"></asp:Label>
                    </ItemTemplate>
                    <EditItemTemplate>
                        <asp:TextBox Text='<%# Eval("Address") %>' Id="txtadd" runat="server"></asp:TextBox>
                    </EditItemTemplate>
                </asp:TemplateField>

                <asp:TemplateField HeaderText="state">
                    <ItemTemplate>
                        <asp:Label Text='<%# Eval("state") %>' Id="lblsta" runat="server"></asp:Label>
                    </ItemTemplate>
                    <EditItemTemplate>
                        <asp:TextBox Text='<%# Eval("state") %>' Id="txtsta" runat="server"></asp:TextBox>
                    </EditItemTemplate>
                </asp:TemplateField>
                
                </Columns>
                </asp:GridView>
        </div>
    </form>
</body>
</html>
